### ISSUE TITLE
how to execute miner.hmtl?

### ISSUE THREAD

**Issue by emonkz** [Jefreesujit/easyminer#2]
Hi newbie here :)

I wanna ask about how to execute miner.html because after I type pool address and then port and then address,I cant connect to miner.html form. But when I tried this to your page https://jefreesujit.github.io/easyminer , eveything is fine.

http://45.77.255.89/miner?pool=trtl.mine2gether.com&port=1115&currency=trtl&address=TRTLv1HRHkYEFHzx2yS8qAjZM3N7ApuQwETcy4WUU5xA1LkB9vKoWAd9cUvsLRq5pbaGjrwkSYaNMDC4SwE6kzDzEydzVAc2sqq

404 Not Found
nginx/1.10.3 (Ubuntu)

Regards,

emonkz

**Comment by Jefreesujit** [comment]
Hi, first of all i m happy that someone had looked into my code! :P 

Well, could you elaborate on what is the actual error? How are you trying to run this application? Did you try changing something in code?

I assume you tried to run the application in your local using a server. Had you tried starting from the index.html page? This app doesnt require a server, so try accessing using the file directly. If that works then the issue would be something related to server.

Hope this helps, if not feel free to bug me ;)

**Comment by emonkz** [comment]
This is my step : 

1. Found your repo :P 

2. Fork 

2. Rent cheap vps for testing

3. Git clone your repo ( I didn't try changing anything something on easyminer code)

4. Install nginx

5. Duplicate all easyminer file into var www html directory

6.  And now I can access from this  http://45.77.255.89

7.  Insert trtl pool url,insert port, change currency into turtle coin, insert address. Click Get Started button.

8. Error 404 not found like this http://45.77.255.89/miner?pool=trtl.mine2gether.com&port=1115&currency=trtl&address=TRTLv1HRHkYEFHzx2yS8qAjZM3N7ApuQwETcy4WUU5xA1LkB9vKoWAd9cUvsLRq5pbaGjrwkSYaNMDC4SwE6kzDzEydzVAc2sqq

**Comment by Jefreesujit** [comment]
Hi, I just took a look at your app, try using this, it should work:

http://45.77.255.89/miner.html?pool=trtl.mine2gether.com&port=1115&currency=trtl&address=TRTLv1HRHkYEFHzx2yS8qAjZM3N7ApuQwETcy4WUU5xA1LkB9vKoWAd9cUvsLRq5pbaGjrwkSYaNMDC4SwE6kzDzEydzVAc2sqq

Since you are trying to run from a nginx server, it is looking for a route called "/miner" which is not available, hence it throws 404 error.

You can do two things:

1) Add a route "/miner" in your server and serve the miner.html as response to that route.
2) Make changes to form action attribute to point to "miner.html" instead of "miner".

Hope this helps. 

PS: If you are interested, i still have some improvements to this app, you can help me build that out. :)
